# Generated by Django 3.1.3 on 2020-11-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
